Models/Product_info.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppArcade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_info()
        {
            this.UserLibraries = new HashSet<UserLibrary>();
        }
    
        public int Product_id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public decimal Product_Price { get; set; }
        public string Product_Category { get; set; }
        public string Product_Description { get; set; }
        public string Product_Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLibrary> UserLibraries { get; set; }
    }
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppArcade.Models;

namespace AppArcade.Controllers
{
    public class CartController : Controller
    {
        private AppArcadeEntities db = new AppArcadeEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddToCart(int productid)
        {


            if (Session["cart"] == null)
            {
                List<Cart> carts = new List<Cart>();

                carts.Add(new Cart() { product = db.Product_info.Find(productid) });
                Session["cart"] = carts;

            }
            else
            {
                List<Cart> carts = (List<Cart>) Session["cart"];
                int Index = IsInCart(productid);
                if (Index != -1)
                {
                    return View();
                }
                else
                {
                    carts.Add(new Cart() { product = db.Product_info.Find(productid) });
                }
                Session["cart"] = carts;
            }
            return RedirectToAction("Index");

        }

        public ActionResult RemoveFromCart(int productid) 
        {
            List<Cart> carts = (List<Cart>)Session["cart"];
            int Index = IsInCart(productid);
            carts.RemoveAt(Index);
            Session["cart"] = carts;
            return RedirectToAction("Index");
        }
        public int IsInCart(int ProductId)
        {
            List<Cart> carts = (List<Cart>)Session["cart"];
            for (int i = 0; i < carts.Count; i++)
            {
                if (carts[i].product.Product_id == ProductId)
                    return i;
            }
            return -1;
        }

        public ActionResult Payment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Payment(String CCV)
        {
            
            Random rnd = new Random();
            int transactionResult = rnd.Next(0, 2);

            if (transactionResult == 1)
            {
                ViewBag.Message = "Payment Successful!";
                
            }
            else
            {
                ViewBag.Message = "Payment Failed. Please try again.";
            }

            return RedirectToAction("Checkout","UserLibraries");
        }

    }
}

Controllers/Product_infoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using AppArcade.Models;

namespace AppArcade.Controllers
{
    public class Product_infoController : Controller
    {
        private AppArcadeEntities db = new AppArcadeEntities();

        // GET: Product_info
        public ActionResult Index( string searching, string category)
        {
            int? userid = Session["SessionId"] as int?;
            var Products = db.Product_info.AsQueryable();

            var libproduct = db.UserLibraries.Where(ul=> ul.USERID ==userid).Select(ul => ul.PRODUCTID).ToList();

            Products = Products.Where(p => !libproduct.Contains(p.Product_id));

            if (!string.IsNullOrEmpty(searching))
            {
                Products = Products.Where(x => x.Product_Name.StartsWith(searching) || searching == null);
            }
            if (!string.IsNullOrEmpty(category))
            {
                Products = Products.Where(x => x.Product_Category.StartsWith(category) || category == null);
            }
            
            return View(Products.ToList());
        }

     
       
        // GET: Product_info/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_info product_info = db.Product_info.Find(id);
            if (product_info == null)
            {
                return HttpNotFound();
            }
            return View(product_info);
        }

        // GET: Product_info/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product_info/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Product_id,Product_Name,Product_Image,Product_Price,Product_Category,Product_Description,Product_Data")] Product_info product_info)
        {
            if (ModelState.IsValid)
            {   
                db.Product_info.Add(product_info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product_info);
        }

        // GET: Product_info/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_info product_info = db.Product_info.Find(id);
            if (product_info == null)
            {
                return HttpNotFound();
            }
            return View(product_info);
        }

        // POST: Product_info/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Product_id,Product_Name,Product_Image,Product_Price,Product_Category,Product_Description,Product_Data")] Product_info product_info)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product_info).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product_info);
        }

        // GET: Product_info/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_info product_info = db.Product_info.Find(id);
            if (product_info == null)
            {
                return HttpNotFound();
            }
            return View(product_info);
        }

        // POST: Product_info/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product_info product_info = db.Product_info.Find(id);
            db.Product_info.Remove(product_info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Product_info/Create.cshtml
@model AppArcade.Models.Product_info

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm(new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <style>
        body {
            background-image: url('https://img.freepik.com/premium-vector/wave-liquid-background-abstract-vibrant-poster-web-element_41901-2696.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        .card-body {
            background-color: rgb(224, 132, 102,0.4);
        }

        .form-control {
            border: 2px solid #808080;
            border-radius: 20px;
            padding: 7px;
            transition: border-color 0.3s ease;
            width: calc(100% - 14px);
            box-sizing: border-box;
            margin-bottom: 10px;
        }

            .form-control:focus {
                outline: none;
                border-color: #ff6a00;
                box-shadow: none;
            }
    </style>

    <div class="container" style="border-radius: 10px;">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card" style="background-color: rgba(255, 255, 255, 0.6);">
                    <div class="card-body">
                        <h4 class="card-title">Add Product</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group" style="margin-bottom: 15px">
                            <p>Product Name</p>
                            @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })

                            @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group" style="margin-bottom: 15px;">
                            @Html.LabelFor(model => model.Product_Image)
                            @Html.EditorFor(model => model.Product_Image, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Product_Image, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group" style="margin-bottom: 15px;">
                            @Html.LabelFor(model => model.Product_Price)
                            @Html.EditorFor(model => model.Product_Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Product_Price, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group" style="margin-bottom: 15px;">
                            @Html.LabelFor(model => model.Product_Category)
                            @Html.EditorFor(model => model.Product_Category, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Product_Category, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group" style="margin-bottom: 15px;">
                            @Html.LabelFor(model => model.Product_Description)
                            @Html.EditorFor(model => model.Product_Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Product_Description, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group" style="margin-bottom: 15px;">
                            @Html.LabelFor(model => model.Product_Data)
                            @Html.EditorFor(model => model.Product_Data, new { htmlAttributes = new { @class = "form-control" } })                            
                            @Html.ValidationMessageFor(model => model.Product_Data, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success btn-lg btn-block shadow-sm" style="border-radius: 25px; padding: 10px 10px; width: 100px; height: 50px; ">Create</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="text-center mt-2">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-outline-primary rounded-pill py-2 px-4 shadow= sm" })
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Product_info/Delete.cshtml
@model AppArcade.Models.Product_info

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product_info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Image)            
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Data)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Product_info/Details.cshtml
@model AppArcade.Models.Product_info

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

    .card {
        background-color: #c79898;
        border: none;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
    }

    .card-body {
        padding: 30px;
    }

    .btn {
        border-radius: 20px;
        padding: 10px 20px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .btn-success {
        background-color: #28a745;
        border-color: #28a745;
    }

        .btn-success:hover {
            background-color: #218838;
            border-color: #218838;
        }

    .btn-secondary {
        background-color: #6c757d;
        border-color: #6c757d;
    }

        .btn-secondary:hover {
            background-color: #5a6268;
            border-color: #5a6268;
        }
</style>


<div class="card">
    <div class="card-body">
        <h4 class="card-title">Product Details</h4>
        <hr />

        <div class="row">
            <div class="col-md-6">
                <dl class="row">
                    <dt class="col-sm-4">Name:</dt>
                    <dd class="col-sm-8" style="font-weight:bold">@Html.DisplayFor(model => model.Product_Name)</dd>

                    <dt class="col-sm-4">Price:</dt>
                    <dd class="col-sm-8" style="color:aquamarine">@Html.DisplayFor(model => model.Product_Price)</dd>

                    <dt class="col-sm-4">Category:</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Product_Category)</dd>

                    <dt class="col-sm-4">Description:</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Product_Description)</dd>

                    @*<dt class="col-sm-4">Data:</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Product_Data)</dd>*@
                </dl>
            </div>

            <div class="col-md-6">
                <img src="@Model.Product_Image" class="img-fluid" alt="Product Image">
            </div>
        </div>
    </div>
</div>

<div class="mt-3">
    @if (Session["SessionId"] == null)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Product_id }, new { @class = "btn btn-primary mr-2" })
    }

    <a href="@Url.Action("AddToCart", "Cart", new { productid = Model.Product_id })" class="btn btn-success">Add to Cart</a>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary ml-2" })
</div>

Views/Product_info/Edit.cshtml
@model AppArcade.Models.Product_info

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product_info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Product_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Image, htmlAttributes: new { @class = "control-label col-md-2" })            
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Product_info/Index.cshtml
@model IEnumerable<AppArcade.Models.Product_info>

@{
    ViewBag.Title = "APPS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .btn-create {
        margin-top: 15px;
        font-weight: bold;
        color: #fff;
        text-decoration: blink;
        background-color: #3c2ff3;
        padding: 10px ;
        border-radius: 20px;
        transition: background-color 0.3s;
    }

        .btn-create:hover {
            background-color: #b0b6e9;
        }

    .search-container {
        position: relative;
        margin: 4%;
    }

    .search-form {
        position:static;
        top: 2px;
        right: px;
        margin-top: 10px;
        z-index: 999;
    }

    .search-field {
        padding: 10px 20px;
        border-radius: 20px;
        border: 1px solid #ccc;
        border-right: none;
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }

    .input-group-append .search-button {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }

    .search-button {
        padding: 10px 20px;
        border-radius: 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s;
        margin-left: -1px;
    }

        .search-button:hover {
            background-color: #0056b3;
        }


    .card {
        border: none;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        background-color: #fff;
        width: 200px;
        margin-bottom: 15px;
        margin-top: 20px;
    }

    .card-body {
        padding: 15px;
        background-color: #f8f9fa;
    }

    .card-title {
        font-weight: bold;
        color: #212529;
        margin-bottom: 10px;
    }

    .product-name {
        font-weight: bold;
        color: #212529;
        margin-bottom: 5px;
    }

    .product-price {
        color: #8b4513;
        margin-bottom: 5px;
    }

    .product-category {
        color: #6c757d;
        margin-bottom: 10px;
    }

    .btn-details {
        margin-top: 10px;
    }

    body {
        background-color: #f0ddcc;
    }
</style>


<div class="row">
    <div class="col">
        @if (Session["SessionId"] == null)
        {
            @*<p class="col-md-3 btn-sm btn-create" style="margin:5%">
                @Html.ActionLink("Create New", "Create")
            </p>*@
            <div class="col ">
                <a href="@Url.Action("Create", "Product_info")" class="btn-sm btn-create">Create New</a>
            </div>
        }
    </div>
<div class="col">
    <div class="search-container">
        <div class="search-form">
            @using (Html.BeginForm("Index", "Product_info", FormMethod.Get))
            {
                <div class="input-group">
                    @Html.TextBox("Searching", null, new { @class = "search-field", placeholder = "Search..." })
                    <div class="input-group-append">
                        <button type="submit" class="search-button">Search</button>
                    </div>
                </div>
            }
        </div>
    </div>
@*@using (Html.BeginForm("Index", "Product_info", FormMethod.Get))
{
    @Html.TextBox("Searching")
    <input type="submit" value="Search" style="margin:5%"/>
}*@
</div>
</div>

@if (Model.Count() == 0)
{
    <p>no match found</p>
}
else
{
    <section class="container">
        <div class="row">
            @foreach (var item in Model)
            {

                <div class="col-md col-sm-6 mb-4">
                    <div class="card" style="width:200px; height:350px">
                        <div class="img-fluid">
                            <img src="@item.Product_Image" style="width:100%; height:200px" />
                        </div>
                        <div class="card-body" style="background-color:ghostwhite">

                            <div>
                                <h4 style="font-weight:bold">@item.Product_Name</h4>
                                <h6 style="color:brown">@item.Product_Price BDT</h6>
                                <h6>@item.Product_Category</h6>
                                <button class="btn btn-outline-primary small">
                                    @Html.ActionLink("Details", "Details", new { id = item.Product_id })
                                </button>
                                
                            </div>
                        </div>
                    </div>
                </div>



            }
        </div>
    </section>
}