Models/admin_info.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppArcade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_info
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminPassword { get; set; }
        public string AdminEmail { get; set; }
    }
}

Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppArcade.Models;

namespace AppArcade.Controllers
{
    public class ChatsController : Controller
    {
        private AppArcadeEntities db = new AppArcadeEntities();

        // GET: Chats/Create
        public ActionResult Create()
        {
            return View(db.Chats.ToList());
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Chat chat)
        {            
            int? id = Session["SessionId"] as int?;
            if (Session["SessionId"]!=null || Session["ASessionId"]!=null)
            { 
                chat.UserId = id;
                chat.Timestamp = DateTime.UtcNow;
                db.Chats.Add(chat);
                db.SaveChanges();                
                
            }
            return View(db.Chats.ToList());
            
        }

    

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/admin_infoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppArcade.Models;

namespace AppArcade.Controllers
{
    public class admin_infoController : Controller
    {
        private AppArcadeEntities db = new AppArcadeEntities();

        // GET: admin_info
        public ActionResult Index()
        {
            return View(db.admin_info.ToList());
        }

        // GET: admin_info/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            admin_info admin_info = db.admin_info.Find(id);
            if (admin_info == null)
            {
                return HttpNotFound();
            }
            return View(admin_info);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(admin_info Admin_Info)
        {
            var admin = db.admin_info.SingleOrDefault(a => a.AdminEmail == Admin_Info.AdminEmail && a.AdminPassword == Admin_Info.AdminPassword);

            if (admin != null)
            {
                Session["ASessionId"] = admin.AdminName;
                return RedirectToAction("Index", "admin_info");
                Response.Write("Good job");
            }
            else
            {
                return HttpNotFound();
            };
            return View();
        }

        // GET: admin_info/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin_info/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdminId,AdminName,AdminPassword,AdminEmail")] admin_info admin_info)
        {
            if (ModelState.IsValid)
            {
                db.admin_info.Add(admin_info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin_info);
        }

        // GET: admin_info/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            admin_info admin_info = db.admin_info.Find(id);
            if (admin_info == null)
            {
                return HttpNotFound();
            }
            return View(admin_info);
        }

        // POST: admin_info/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdminId,AdminName,AdminPassword,AdminEmail")] admin_info admin_info)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin_info).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin_info);
        }

        // GET: admin_info/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            admin_info admin_info = db.admin_info.Find(id);
            if (admin_info == null)
            {
                return HttpNotFound();
            }
            return View(admin_info);
        }

        // POST: admin_info/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            admin_info admin_info = db.admin_info.Find(id);
            db.admin_info.Remove(admin_info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/admin_info/Create.cshtml
@model AppArcade.Models.admin_info

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>admin_info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AdminName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdminPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdminEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/admin_info/Delete.cshtml
@model AppArcade.Models.admin_info

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>admin_info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AdminName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminEmail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/admin_info/Details.cshtml
@model AppArcade.Models.admin_info

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>admin_info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AdminName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminEmail)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AdminId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/admin_info/Edit.cshtml
@model AppArcade.Models.admin_info

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .btn-primary {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 30px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 25px;
    }

        .btn-primary:hover {
            background-color: #45a049;
        }

    .btn-secondary {
        background-color: #008CBA;
        border: none;
        color: white;
        padding: 10px 30px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 25px;
    }

        .btn-secondary:hover {
            background-color: #0077A7;
        }
</style>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <h4>Edit Admin Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AdminId)

        <div class="row">
            <div class="col-md-6">
                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.AdminName, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.AdminName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdminName, "", new { @class = "text-danger" })
                </div>

                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.AdminPassword, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.AdminPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdminPassword, "", new { @class = "text-danger" })
                </div>

                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.AdminEmail, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.AdminEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdminEmail, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary me-2">Save</button>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/admin_info/Index.cshtml
@model IEnumerable<AppArcade.Models.admin_info>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["ASessionId"] == null)
{
    /*<p>@Html.ActionLink("Login", "Login", "user_info")</p>*/
    <h4>Session Expired</h4>
    <p>Please Login</p>
}
else
{
    <div class="welcome-header">
        <h2>Welcome, @Session["ASessionId"]!</h2>
        @using (Html.BeginForm("ALogout", "Home", FormMethod.Post, new { @class = "logout-form" }))
        {
            <input type="submit" value="Logout" class="btn btn-success" />
        }
    </div>   
}

@if (Session["ASessionId"] != null)
{  
    <table class="table table-striped table-bordered" style="margin-top:5%">
        <thead class="thead-dark">
            <tr class="text-center">
                <th>Admin Name</th>
                <th>Password</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.AdminName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdminPassword)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdminEmail)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.AdminId }, new {@class = "btn btn-info"}) @*|
                    @Html.ActionLink("Details", "Details", new { id = item.AdminId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.AdminId })*@
                </td>
            </tr>
        }

    </table>

    <div class="col-sm-3" style="width:130px;margin-top:20%; margin-bottom:15%">
        <div class="card" style="border-radius:20px">
            <a href="@Url.Action("Create", "Chats")" style="text-decoration:none" />
            <button class="card-body" type="button" style="background-color: #fea8a8; border-radius: 20px">
                <img src="https://cdn1.iconfinder.com/data/icons/user-worker-employee-business-avatars/100/26-1User_34-1024.png" class="card-img-top" />
                <h5 class="card-title" style="font-weight:bold;font-size:small">support</h5>
            </button>
        </div>
    </div>    
}

<style>
    .welcome-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 20px;
        background-color: #debebe;
        border-radius: 10px;
        margin-bottom: 20px;
    }

        .welcome-header h2 {
            font-size: 24px;
            font-family: 'Segoe UI';
            font-weight: bold;
        }

    .logout-form {
        margin: 0;
    }
</style>

Views/admin_info/Login.cshtml
@model AppArcade.Models.admin_info

@{
    ViewBag.Title = "Admin_Login";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin Login</title>
    <style>
        body {
            background-image: url('https://i.pinimg.com/736x/c7/39/83/c739830ada7ea71fefed868be577b57c.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            font-family: Arial, sans-serif,'Segoe UI', Tahoma, Geneva, Verdana;
            margin: 0;
            padding: 0;
            display: block;
            justify-content: center;
            align-items: center;
        }

        .login-container {
            max-width: 400px;
            margin: 100px auto;
            background-color: rgb(255, 255, 255, 0.5);
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

            .login-container h4 {
                color: #333333;
                font-weight: bold;
                margin-bottom: 30px;
                text-align: center;
            }

            .login-container .form-group label {
                color: #666666;
                font-weight: bold;
            }

            .login-container .form-control {
                border: 2px solid #E5CFF7;
                border-radius: 25px;
                padding: 20px;
                transition: border-color 0.3s ease;
                width: 100%;
                box-sizing: border-box;
                margin-bottom: 20px;
            }

            .login-container .btn-login {
                background-color: rgb(0, 0, 0);
                color: #fff;
                border: none;
                border-radius: 30px;
                padding: 10px 10px;
                cursor: pointer;
                transition: background-color 0.3s ease;
                width: 150px;
                height: 50px;
                margin: 0 auto;
                display: block;
            }

                .login-container .btn-login:hover {
                    background-color: #218838;
                }

            .login-container .text-danger {
                color: #dc3545;
                font-size: 14px;
            }
    </style>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <div class="login-container">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <h4>Admin Login</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.AdminEmail)
                @Html.EditorFor(model => model.AdminEmail, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your email" } })
                @Html.ValidationMessageFor(model => model.AdminEmail, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AdminPassword)
                @Html.EditorFor(model => model.AdminPassword, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your password", type = "password" } })
                @Html.ValidationMessageFor(model => model.AdminPassword, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-login">Login</button>
            </div>
        }
    </div>

</body>
</html>